# Generated by Django 6.0.1 on 2026-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
    ]
